package net.sumppen.whatsapi4j;

public enum SyncType {
	FULL_REGISTRATION, FULL_INTERACTIVE, FULL_BACKGROUND, DELTA_INTERACTIVE, DELTA_BACKGROUND, QUERY_INTERACTIVE, CHUNKED_REGISTRATION, CHUNKED_INTERACTIVE, CHUNKED_BACKGROUND

}
